# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-21 13:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_download', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_model',
            name='storage',
            field=models.FileField(default=datetime.datetime(2017, 6, 21, 13, 51, 14, 695529, tzinfo=utc), upload_to='storage'),
            preserve_default=False,
        ),
    ]
